# Generated by Django 4.2.18 on 2025-02-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
